"""step temperature columns update

Revision ID: 20240605_step_temperature_columns_update
Revises: 4b6c3d56bab9
Create Date: 2025-06-05 10:00:00.000000

"""
revision = '20240605_step_temperature_columns_update'
down_revision = '4b6c3d56bab9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###