"""Add nominal_capacity and nominal_voltage to cell

Revision ID: 30680ae52399
Revises: 82b95d02febb
Create Date: 2025-05-20 15:38:25.671193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30680ae52399'
down_revision: Union[str, None] = '82b95d02febb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cell', sa.Column('nominal_capacity', sa.Float(), nullable=True))
    op.add_column('cell', sa.Column('nominal_voltage', sa.Float(), nullable=True))
    op.add_column('cell', sa.Column('form_factor', sa.Enum('PRISMATIC', 'CYLINDRICAL', 'POUCH', 'OTHER', name='cellformfactor'), nullable=True))
    op.add_column('cell', sa.Column('serial_number', sa.String(), nullable=True))
    op.add_column('cell', sa.Column('date_received', sa.DateTime(), nullable=True))
    op.add_column('cell', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('cell', 'capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cell', 'form',
               existing_type=postgresql.ENUM('PRISMATIC', 'CYLINDRICAL', 'POUCH', 'OTHER', name='cellformfactor'),
               nullable=True)
    op.alter_column('measurement', 'execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('measurement', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('measurement', 'execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cell', 'form',
               existing_type=postgresql.ENUM('PRISMATIC', 'CYLINDRICAL', 'POUCH', 'OTHER', name='cellformfactor'),
               nullable=False)
    op.alter_column('cell', 'capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('cell', 'notes')
    op.drop_column('cell', 'date_received')
    op.drop_column('cell', 'serial_number')
    op.drop_column('cell', 'form_factor')
    op.drop_column('cell', 'nominal_voltage')
    op.drop_column('cell', 'nominal_capacity')
    # ### end Alembic commands ###
