"""remove ocv from step table

Revision ID: 74f5adfba7d1
Revises: de227a3297e5
Create Date: 2025-05-28 09:10:56.341790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f5adfba7d1'
down_revision: Union[str, None] = 'de227a3297e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'ocv')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('ocv', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
