"""remove soc from measurement table

Revision ID: 83131810bc2b
Revises: de4b58ac3df6
Create Date: 2025-05-28 17:18:59.504537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '83131810bc2b'
down_revision: Union[str, None] = 'de4b58ac3df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'soc')
    # SQLite doesn't support ALTER COLUMN DROP NOT NULL, so we skip the data_meta change
    # op.alter_column('step', 'data_meta',
    #            existing_type=sqlite.JSON(),
    #            nullable=True)
    # op.create_foreign_key(None, 'step', 'experiment', ['experiment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'step', type_='foreignkey')
    # op.alter_column('step', 'data_meta',
    #            existing_type=sqlite.JSON(),
    #            nullable=False)
    op.add_column('measurement', sa.Column('soc', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
