"""Rename data_meta to step_name in Step table

Revision ID: fb99222f8260
Revises: 362f8ed7b50a
Create Date: 2025-07-08 14:13:48.776513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb99222f8260'
down_revision: Union[str, None] = '362f8ed7b50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'data_meta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('data_meta', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
